spring.application.name=geektext-api
spring.datasource.url=jdbc:postgresql://localhost:5432/geektext
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD:postgres}
spring.jpa.hibernate.ddl-auto=validate